name: Build Frontend

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # Si no usas bundler, copiamos manualmente los archivos a dist
      - name: Preparar carpeta dist
        run: |
          mkdir dist
          cp home.html dist/
          cp -r Modelo dist/
          cp -r Controlador dist/

      - name: Verificar contenido de dist
        run: ls -R dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: ./dist