name: Deploy Frontend

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: sa-east-1
  S3_BUCKET: frontend-web-ventas
  CLOUDFRONT_ID: EBDU9LF00Q6A6

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://d3122ce2v027je.cloudfront.net

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::897649280051:role/github-actions-frontend-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ./dist
      - name: Borrar home.html viejo
        run: |
          aws s3 rm s3://${{ env.S3_BUCKET }}/home.html
      - name: Sync to S3
        run: |
          aws s3 sync ./dist s3://${{ env.S3_BUCKET }} --delete --exact-timestamps --exclude ".git/*" --exclude ".github/*"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_ID }} \
            --paths "/home.html"
