name: CI/CD Pipeline

on:
  push:
    branches: [master]  # o main, según tu repo

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml